#ifndef BUFFER_CLEAR_TYPES_H
#define BUFFER_CLEAN_TYPES_H
#include <GL/glew.h>
	enum class BufferClear : int{
		ALL_BUFFERS = GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT | GL_ACCUM_BUFFER_BIT,
		COLOR_DEPTH_BUFFERS = GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT,
		COLOR_DEPTH_STENCIL_BUFFERS = GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT,
		COLOR_STENCIL_BUFFERS = GL_COLOR_BUFFER_BIT | GL_STENCIL_BUFFER_BIT,
		COLOR_BUFFER = GL_COLOR_BUFFER_BIT,
		DEPTH_BUFFER = GL_DEPTH_BUFFER_BIT,
		STENCIL_BUFFER = GL_STENCIL_BUFFER_BIT,
		ACCUM_BUFFER = GL_ACCUM_BUFFER_BIT
	};
#endif
