#ifndef FRAMEBUFFER_ATTACH_TARG_H
#define FRAMEBUFFER_ATTACH_TARG_H

enum class FrameBufferAttachment : int {
	COLOR_ATTACHMENT0 = GL_COLOR_ATTACHMENT0,
	DEPTH_ATTACHMENT = GL_DEPTH_ATTACHMENT,
	STENCIL_ATTACHMENT = GL_STENCIL_ATTACHMENT,
	DEPTH_STENCIL_ATTACHMENT = GL_DEPTH_STENCIL_ATTACHMENT
};

#endif
