#ifndef GETPARAM_H
#define GETPARAM_H
#include <GL/glew.h>

// GetParameter. Used as argument in device->GetFunctions
// TODO: Finish this argument list...
enum class GetParam: int{
	ACTIVE_TEXTURE = GL_ACTIVE_TEXTURE,
	BUFFER_BINDING = GL_ARRAY_BUFFER_BINDING,
	INDEX_BUFFER_BINDING = GL_ELEMENT_ARRAY_BUFFER_BINDING,
	BLEND_ENABLED = GL_BLEND,
	CULL_FACE = GL_CULL_FACE,
	CULL_MODE = GL_CULL_FACE_MODE,
	CURRENT_PROGRAM = GL_CURRENT_PROGRAM,
	DEPTH_TEST = GL_DEPTH_TEST,
	DOUBLEBUFFER = GL_DOUBLEBUFFER,
	LINE_WIDTH = GL_LINE_WIDTH,
	MAJOR_VERSION = GL_MAJOR_VERSION,
	MINOR_VERSION = GL_MINOR_VERSION,
	MAX_3DT_SIZE = GL_MAX_3D_TEXTURE_SIZE,
	MAX_FRAG_UNI_BLOCKS = GL_MAX_FRAGMENT_UNIFORM_BLOCKS,
	MAX_FRAMEBUFFER_WIDTH = GL_MAX_FRAMEBUFFER_WIDTH,
	MAX_FRAMEBUFFER_HEIGHT = GL_MAX_FRAMEBUFFER_HEIGHT,
	MAX_PRG_BIN_FMT = GL_NUM_PROGRAM_BINARY_FORMATS,
	MAX_SDR_BIN_FMT = GL_NUM_SHADER_BINARY_FORMATS,
	POINT_SIZE = GL_POINT_SIZE
};

#endif
